# Generated by Django 3.2.9 on 2021-12-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('piso', models.CharField(max_length=3)),
                ('description', models.TextField()),
                ('caracteristicas', models.TextField()),
                ('precio_diario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('O', 'Ocupada'), ('L', 'Libre'), ('A', 'Alquiler')], default='L', max_length=15)),
                ('tipo_habitación', models.CharField(choices=[('I', 'Individual'), ('D', 'Doble'), ('S', 'Suite'), ('P', 'Presidencial')], default='I', max_length=20)),
            ],
            options={
                'verbose_name': 'Habitacion',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
    ]
