# Generated by Django 3.2.9 on 2021-12-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
